[[websites]]
  url = "www.luoxia.com"  
  # 判定标题的
  # 判定文章的(例如:br / b ....)
  [[websites.body.content]]
    name = "p"
    attrs = {class = false}
  # 防止有多级的url 下一页下一章混着
  [[websites.body.next]]
    name = 'a'
    attrs = {rel = "next"}    

[[websites]]
  url = "www.xbookcn.com"
  # 空 就是不管了
  # 其他就是直接指定
  encoding = "big5"
  [[websites.body.content]]
    name = "p"
    attrs = {class = false}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
  [websites.body.index]
    name = 'a'
    string = "目錄頁"
  [[websites.index.content]]
    name = 'a'
    key = "href"    

[[websites]]
  url = "www.mfxsydw.com"
  [[websites.body.content]]
    name = "p"
    attrs = {class = false}
  [[websites.body.next]]
    name = 'a'
    attrs = {rel = "next"}
  
[[websites]]
  # 这货有func但是错误的mmp
  url = "www.piaotian.com"
  [[websites.body.content]]
    name = "br"
    attrs = {class = false}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "m.qu.la"
  [[websites.body.content]]
    name = "div"
    attrs = {}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "www.176novel.com"
  encoding = "gbk"
  [[websites.body.content]]
    name = "div"
    attrs = {id = "nr1"}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "m.hunhun520.com"
  [[websites.body.content]]
    name = "div"
    attrs = {id = "content"}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "www.luoqiu.com"
  encoding = "gbk"
  [[websites.body.content]]
    name = "div"
    attrs = {id = "content"}
  [[websites.body.content]]
    name = "br"
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "www.69shu.com"
  encoding = "gbk"
  [[websites.body.content]]
    name = "div"
    attrs = {class = "yd_text2"}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
        
[[websites]]
  url = "m.00xs.cc"
  encoding = "gbk"
  [[websites.body.content]]
    name = "div"
    attrs = {id = "nr1"}
  [[websites.body.next]]
    name = 'a'
    string = "继续看"
    
[[websites]]
  url = "m.snwx8.com"
  encoding = "gbk"
  [[websites.body.content]]
    name = "div"
    attrs = {id = "nr1"}
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "www.xitxt.net"
  encoding = 'gbk'
  [[websites.body.content]]
    name = "article"
  [[websites.body.next]]
    name = 'a'
    string = "下一"

# 作废,网站搞得麻烦,时效+固定书目,除非js了    
[[websites]]
  url = "m.123du.cc"
  # 自己抓包刷新
  headers = {cookie = "nxgmnmry=22b1144258bb2b3c"}
  [[websites.body.content]]
    name = "div"
    attrs = {class = "TxtContent"}
  [[websites.body.content]]
    name = "br"
  [[websites.body.next]]
    name = 'a'
    string = "下一[页頁]"
  [[websites.body.next]]
    name = 'a'
    string = "下一章"
    
[[websites]]
  url = "m.176xsw.com"
  [[websites.body.content]]
    name = "div"
    attrs = {class = "readcontent"}
  [[websites.body.next]]
    name = 'a'
    string = "下一"  
    
[[websites]]
  url = "e-hentai.org"
  [[websites.body.content]]
    name = "img"
    attrs = {id = "img"}
    key = "src"
  [[websites.body.next]]
    name = 'a'
    attrs = {id = "next"}
    
[[websites]]
  url = "m.k886.net"
  [[websites.body.content]]
    name = "img"
    attrs = {alt = true, height = false}
    key = "src"
  [[websites.body.next]]
    name = 'a'
    string = "下一[页頁]"
  [[websites.body.next]]
    name = 'a'
    string = "下一章"
    
[[websites]]
  url = "raws.mangazuki.co"  
  [[websites.body.content]]
    name = "img"
    attrs = {class = "img-responsive", data-src = true}
    key = "data-src"
  [[websites.body.next]]
    re_body = "var[ ]*next_chapter[^;]+\"(.+)\""
    
[[websites]]
  url = "www.177pic.info"
  [[websites.body.content]]
    name = "img"
    attrs = {class = true}
    key = "src"
  [[websites.body.next]]
    name = 'a'
    string = "下一"
    
[[websites]]
  url = "manhwahand.com"
  [[websites.body.content]]
    name = "img"
    attrs = {class = true, id = true}
    key = "src"
  [[websites.body.next]]
    name = 'a'
    attrs = {class = "btn next_page"}
    
[[websites]]
  url = "nhentai.net"
  [[websites.body.content]]
    name = "img"
    attrs = {class = true}
    key = "src"
  [[websites.body.next]]
    name = 'a'
    attrs = {class = "next"}
    
# 可以认为这是个default设置
[[websites]]
  url = "."
  encoding = "utf-8"
  [websites.body.title]
    name = "title"
  [[websites.body.content]]
    name = "p"
    attrs = {class = false}
  [[websites.body.next]]
    name = 'a'
    attrs = {rel = "next"}
